### ISSUE TITLE
Fail to install with Cordova 10

### ISSUE THREAD

**Issue by jammind** [raphinesse/cordova-plugin-exclude-files#9]
It used to work with Cordova 8 + iOS Platform 4. After I have upgraded it to Cordova 10 + iOS Platform 6, it fails at installation with the following error.

```
Failed to install 'cordova-plugin-exclude-files': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/jam/Documents/Tinkamo/Dev/app-all/plugins/cordova-plugin-exclude-files/scripts/install-deps.js:4:21)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:136:12)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:108:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by raphinesse** [comment]
Thanks for reporting this issue.

It looks like you are using an older version of the plugin which indeed is not compatible with more recent Cordova versions. Please try again with the latest version of the plugin.

Please let me know if that resolved your issue.

**Comment by jammind** [comment]
I have already tried to install the latest version, cordova plugin add cordova-plugin-exclude-files@^0.4.3. But I still got the same error.

**Comment by raphinesse** [comment]
The latest version is in fact 1.0.1. The reason why you were not getting it however, was an error on my side. I recently released 0.4.3 as a patch to the old 0.4.2 version. Unfortunately npm always sets the most recently released version as `latest`, which is why you got 0.4.3 instead of 1.0.1.

I now changed `latest` back to 1.0.1 and you should get that version now if installing `cordova-plugin-exclude-files@latest`. I hope this fixes your issue. Please let me know and thanks again for reporting this.

**Comment by jammind** [comment]
Thx for the note. I managed to install the plugin. I have such codes in config.xml. It used to work and I could see the log of deleted files during **cordova prepare** before. But this time, it doesn't work.
```
    <exclude-files pattern="**/*.scss" />
    <exclude-files pattern="styleguide" />
```

**Comment by raphinesse** [comment]
Great to hear that we could resolve the original problem!

Unfortunately, I cannot reproduce your other problem. The following works as expected for me, using Cordova 10:

```bash
# Setup
cordova create foo && cd foo
cordova platform add browser
cordova plugin add cordova-plugin-exclude-files

# Create www/styleguide
touch www/styleguide

# Add <exclude-files pattern="styleguide" /> as last element to <widget> in config.xml
sed -i '/^<\/widget>/i <exclude-files pattern="styleguide" />' config.xml 

cordova prepare
# Output:
# Excluded following paths from browser build:
#  /tmp/tmp.QoWFPhpmvL/foo/platforms/browser/www/styleguide
```

I am closing this issue, as the original problem has been resolved. If you can provide reproduction steps for your second problem, please do so in a new issue.

**Comment by jammind** [comment]
I did exactly the same as you did, but I still didn't work out. I even tried re-installing Cordova. Is there any dependent component that might affect how it works?

**Comment by raphinesse** [comment]
> I did exactly the same as you did

So I guess your OS is Linux or macOS?

> Is there any dependent component that might affect how it works?

Well, OS, npm and Node.js versions could all play a role. But if you can run Cordova 10 these should be fine. Just to make sure, please run `cordova info` after the above commands and share it here.

Other than that I can only suggest you put a few `console.log` statements in the files in `plugins/cordova-plugin-exclude-files/scripts` and try to see if it runs at all or how far it gets (entry point is in `exclude-files.js`). Maybe this will reveal something.

**Comment by jammind** [comment]
Indeed, there is something wrong with my node modules. I can't even run npm. Re-installing Node.js didn't solve the problem. It is definitely not about your plug-in. But do you have any suggestions?
```
% cordova info
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/usr/local/lib/node_modules/cordova/node_modules/graceful-fs/polyfills.js:10:19)
    at Function.module.exports.sync (/usr/local/lib/node_modules/cordova/node_modules/locate-path/index.js:16:16)
    at Function.module.exports.sync (/usr/local/lib/node_modules/cordova/node_modules/find-up/index.js:38:27)
    at Function.module.exports.sync (/usr/local/lib/node_modules/cordova/node_modules/pkg-up/index.js:5:37)
    at new Conf (/usr/local/lib/node_modules/cordova/node_modules/conf/index.js:21:25)
    at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:40:35)
    at new RelentlessInsight (/usr/local/lib/node_modules/cordova/src/telemetry.js:31:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:1075:30) {
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}
```

**Comment by jammind** [comment]
Here is the `cordova info` output

---
6.0.0
6.0.0
Android Studio project detected

Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    android: 7.1.4
    browser: null
    ios: 6.1.1

Project Installed Plugins:

    com.cordova.speech: 1.0.1
    com.tinkamo.audioinput: 0.3.0
    com.tinkamo.canvascamera: 1.1.5
    com.tinkamo.media: 2.1.1
    com.tinkamo.tflow.screenshot: 0.1
    cordova-open-native-settings: 1.5.2
    cordova-plugin-android-permissions: 1.0.2
    cordova-plugin-bluetoothle: 6.0.0
    cordova-plugin-buildinfo: 4.0.0
    cordova-plugin-compat: 1.2.0
    cordova-plugin-device: 2.0.3
    cordova-plugin-exclude-files: 1.0.1
    cordova-plugin-file: 6.0.2
    cordova-plugin-inappbrowser: 4.0.0
    cordova-plugin-insomnia: 4.3.0
    cordova-plugin-ios-disableshaketoedit: 1.0.0
    cordova-plugin-keyboard: 1.2.0
    cordova-plugin-splashscreen: 6.0.0
    cordova-plugin-statusbar: 2.4.3
    cordova-plugin-touch-id: 3.3.1
    cordova-plugin-whitelist: 1.3.4
    cordova-plugin-zip: 3.1.0
    ios-permissions-vitta: 0.0.3

Environment:

    OS: macOS Catalina 10.15.6 (19G2021) (darwin 19.6.0) x64
    Node: v14.11.0
    npm: 6.14.8

android Environment:

    android:
ERROR: Command failed with ENOENT: android list target
spawn android ENOENT


ios Environment:

    xcodebuild:
Xcode 12.0
Build version 12A7209


Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.tinkamo.tinkamoallapp" version="2.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Tinkamo All</name>
    <description>
        Fun way to code.
    </description>
    <author email="info@tinkamo.com" href="https://tinkamo.com">
        Team Tinkamo
    </author>
    <content src="index.html" />
    <preference name="scheme" value="app" />
    <preference name="hostname" value="localhost" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="Fullscreen" value="false" />
    <access origin="*" />
    <allow-navigation href="http://*.tinkamo.com/*" />
    <allow-navigation href="https://*.tinkamo.com/*" />
    <allow-navigation href="http://*.tinkamo.cn/*" />
    <allow-navigation href="https://*.tinkamo.cn/*" />
    <allow-intent href="http://*.tinkamo.com/*" />
    <allow-intent href="https://*.tinkamo.com/*" />
    <allow-intent href="http://*.tinkamo.cn/*" />
    <allow-intent href="https://*.tinkamo.cn/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <exclude-files pattern="**/*.scss" />
    <exclude-files pattern="god" />
    <exclude-files pattern="styleguide" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="BackupWebStorage" value="local" />
        <preference name="EnableWebGL" value="true" />
        <preference name="DisallowOverscroll" value="true" />
        <preference name="Orientation" value="default" />
        <preference name="StatusBarBackgroundColor" value="#000000" />
        <preference name="AllowInlineMediaPlayback" value="true" />
        <access launch-external="yes" origin="mailto:*" />
        <config-file parent="NSBluetoothAlwaysUsageDescription" target="*-Info.plist">
            <string>智能积木需要蓝牙无线连接才能编程</string>
        </config-file>
        <config-file parent="NSBluetoothPeripheralUsageDescription" target="*-Info.plist">
            <string>智能积木需要蓝牙无线连接才能编程</string>
        </config-file>
        <config-file parent="NSCameraUsageDescription" target="*-Info.plist">
            <string>人脸传感器需要使用摄像头</string>
        </config-file>
        <config-file parent="NSFaceIDUsageDescription" target="*-Info.plist">
            <string>演示模式使用指纹/人脸ID防止程序被篡改</string>
        </config-file>
        <config-file parent="NSMicrophoneUsageDescription" target="*-Info.plist">
            <string>扬声器模块需要麦克风录制自己的音</string>
        </config-file>
        <config-file parent="NSSpeechRecognitionUsageDescription" target="*-Info.plist">
            <string>语音传感器需要使用语音识别</string>
        </config-file>
        <config-file parent="UIFileSharingEnabled" target="*-Info.plist">
            <string>YES</string>
        </config-file>
        <splash src="res/screen/ios/Default@2x~universal~anyany.png" />
    </platform>
    <plugin name="com.cordova.speech" spec="../plugin-source/speech" />
    <plugin name="com.tinkamo.audioinput" spec="../plugin-source/audioinput" />
    <plugin name="com.tinkamo.canvascamera" spec="../plugin-source/canvas-camera-plugin" />
    <plugin name="com.tinkamo.media" spec="../plugin-source/media" />
    <plugin name="com.tinkamo.tflow.screenshot" spec="../plugin-source/screenshot" />
    <plugin name="cordova-open-native-settings" spec="../plugin-source/cordova-open-native-settings" />
    <plugin name="cordova-plugin-android-permissions" spec="../plugin-source/cordova-plugin-android-permissions" />
    <plugin name="cordova-plugin-bluetoothle" spec="^6.0.0" />
    <plugin name="cordova-plugin-buildinfo" spec="^4.0.0" />
    <plugin name="cordova-plugin-compat" spec="^1.2.0" />
    <plugin name="cordova-plugin-device" spec="^2.0.3" />
    <plugin name="cordova-plugin-exclude-files" spec="^1.0.1" />
    <plugin name="cordova-plugin-file" spec="^6.0.2" />
    <plugin name="cordova-plugin-inappbrowser" spec="^4.0.0" />
    <plugin name="cordova-plugin-insomnia" spec="https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git" />
    <plugin name="cordova-plugin-ios-disableshaketoedit" spec="^1.0.0" />
    <plugin name="cordova-plugin-keyboard" spec="^1.2.0" />
    <plugin name="cordova-plugin-splashscreen" spec="^6.0.0" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.3" />
    <plugin name="cordova-plugin-touch-id" spec="^3.3.1" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.4" />
    <plugin name="cordova-plugin-zip" spec="^3.1.0" />
    <plugin name="ios-permissions-vitta" spec="../plugin-source/ios-permissions-vitta" />
    <engine name="android" spec="7.1.4" />
    <engine name="ios" spec="^6.1.0" />
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "platforms": [
    "android",
    "ios",
    "browser"
  ],
  "plugins": {
    "com.cordova.speech": {},
    "com.tinkamo.audioinput": {},
    "com.tinkamo.canvascamera": {},
    "com.tinkamo.tflow.screenshot": {},
    "cordova-open-native-settings": {},
    "cordova-plugin-android-permissions": {},
    "cordova-plugin-bluetoothle": {},
    "cordova-plugin-buildinfo": {},
    "cordova-plugin-compat": {},
    "cordova-plugin-device": {},
    "cordova-plugin-file": {},
    "cordova-plugin-inappbrowser": {},
    "cordova-plugin-insomnia": {},
    "cordova-plugin-ios-disableshaketoedit": {},
    "cordova-plugin-keyboard": {},
    "cordova-plugin-splashscreen": {},
    "cordova-plugin-statusbar": {},
    "cordova-plugin-whitelist": {},
    "cordova-plugin-zip": {},
    "ios-permissions-vitta": {},
    "com.tinkamo.media": {},
    "cordova-plugin-touch-id": {
      "FACEID_USAGE_DESCRIPTION": "演示模式使用指纹/人脸ID防止程序被篡改"
    },
    "cordova-plugin-exclude-files": {}
  }
}
--- End of Cordova JSON Snippet ---

**Comment by raphinesse** [comment]
The info you provided is obviously from a bigger project. Can you please verify that the bug described by you exists _in a new, minimal Cordova project, as created by my instructions above_? There could be any number of things going wrong with that many plugins.

**Comment by jammind** [comment]
My mistake. Here it is.

---

```
% cordova info
6.0.0
6.0.0

Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    browser: null

Project Installed Plugins:

    cordova-plugin-whitelist: 1.3.4

Environment:

    OS: macOS Catalina 10.15.6 (19G2021) (darwin 19.6.0) x64
    Node: v14.11.0
    npm: 6.14.8

Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <exclude-files pattern="styleguide" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "plugins": {
    "cordova-plugin-whitelist": {}
  },
  "platforms": [
    "browser"
  ]
}
--- End of Cordova JSON Snippet ---
```

**Comment by raphinesse** [comment]
`cordova-plugin-exclude-files` seems not to be installed in above project
